# render.yaml
# This file tells Render how to deploy your application.

services:
  - type: web
    name: tko-scanner
    env: python
    plan: free # You can upgrade this later if you need more resources
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.server:app"
    envVars:
      - key: AIRTABLE_BASE_ID
        fromEnv: AIRTABLE_BASE_ID
      - key: AIRTABLE_TABLE_NAME
        fromEnv: AIRTABLE_TABLE_NAME
      - key: AIRTABLE_TOKEN # Set this in Render's Environment settings
        sync: false
      - key: SYNC_PASSWORD # Set this in Render's Environment settings
        sync: false
      - key: SUPABASE_URL # Set this in Render's Environment settings
        sync: false
      - key: SUPABASE_SERVICE_KEY # Set this in Render's Environment settings
        sync: false
